USE [master]
GO

/****** Object:  Database [OverSurgery]    Script Date: 1/11/2017 10:37:03 AM ******/
CREATE DATABASE [OverSurgery]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OverSurgery', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OverSurgery.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OverSurgery_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OverSurgery_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [OverSurgery] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OverSurgery].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OverSurgery] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OverSurgery] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OverSurgery] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OverSurgery] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OverSurgery] SET ARITHABORT OFF 
GO

ALTER DATABASE [OverSurgery] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OverSurgery] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OverSurgery] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OverSurgery] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OverSurgery] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OverSurgery] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OverSurgery] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OverSurgery] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OverSurgery] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OverSurgery] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OverSurgery] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OverSurgery] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OverSurgery] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OverSurgery] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OverSurgery] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OverSurgery] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OverSurgery] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OverSurgery] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OverSurgery] SET  MULTI_USER 
GO

ALTER DATABASE [OverSurgery] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OverSurgery] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OverSurgery] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OverSurgery] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OverSurgery] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OverSurgery] SET QUERY_STORE = OFF
GO

USE [OverSurgery]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OverSurgery] SET  READ_WRITE 
GO


